{% set name = "cuda-cccl" %}
{% set version = "13.3.4.2.1" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-sbsa" %}  # [aarch64 and arm_variant_type=="sbsa"]
{% set platform = "linux-aarch64" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "sbsa-linux" %}  # [aarch64 and arm_variant_type=="sbsa"]
{% set target_name = "aarch64-linux" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set target_name = "x64" %}  # [win64]
{% set target_name = "arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

{% set platform = platform | default("linux-x86_64", true) %}
{% set major = load_file_regex(load_file="lib/cmake/cccl/cccl-config-version.cmake", regex_pattern="CCCL_VERSION_MAJOR[ \t]+([0-9]+)") %}
{% set minor = load_file_regex(load_file="lib/cmake/cccl/cccl-config-version.cmake", regex_pattern="CCCL_VERSION_MINOR[ \t]+([0-9]+)") %}
{% set patch = load_file_regex(load_file="lib/cmake/cccl/cccl-config-version.cmake", regex_pattern="CCCL_VERSION_PATCH[ \t]+([0-9]+)") %}
{% set cccl_version = (major.group(1) ~ "." ~ minor.group(1) ~ "." ~ patch.group(1)) if major else "0.0.0" %}
{% set sha256 = "7c973e70d8f8d732f801fe2297c9cb5a541f22824fa6ad64ac4f0e183f9c4397" %}  # [linux64]
{% set sha256 = "36fe2aa9e58a6c924c609e41b466d4ec5c7f66db2f171a7b0ecdd8482274213e" %}  # [aarch64 and arm_variant_type=="sbsa"]
#{% set sha256 = "296248ed702ea9e1a5e43c367d7a09a9ce2fda8a8c21101c428ea79eecf1a46c" %}  # [aarch64 and arm_variant_type=="tegra"]
{% set sha256 = "ea3ebdd98d4d98819cc26b66bc5a0931004ed35ff18eea8b93e0bd2c8bfa5d7c" %}  # [win64]
{% set sha256 = "e8a7c96268ae6c52a7b8b07d96e1f84ab8eae5619c3b989024ce712dda5c2cc2" %}  # [win and arm64]

# CUDA C++ Core Libraries (CCCL) includes thrust, cub, and libcudacxx. These are header-only libraries.
# The cccl package ships CCCL headers in the environment's include directory for use in downstream recipes that require CCCL. It follows CCCL upstream versioning. Use this package to say, "I want a specific version of CCCL headers when building my package (which may be newer than the versions shipped in the latest CUDA Toolkit)."
# The cuda-cccl_{{ target_platform }} package (e.g. cuda-cccl_linux-64) ships CCCL headers in 'targets/.../include' that can be used by nvcc, the CUDA compiler. It follows CUDA Toolkit versioning. This package should only be a dependency of the cuda-cudart / cuda-nvcc packages that require CCCL to function. It is target-specific to allow for cross-compilation, as a dependency of cuda-nvcc.
# The cuda-cccl package is a metapackage that depends on cccl and cuda-cccl_{{ target_platform }} to ensure that versions are consistent. Use this package to say, "I want to build with the thrust headers that shipped with CUDA Toolkit X.Y" by adding dependencies on `cuda-cccl` and `cuda-version X.Y`.

package:
  name: cuda-cccl-split
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cccl/{{ platform }}/cccl-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [osx or ppc64le]

outputs:
  - name: cuda-cccl
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - cuda-cccl_{{ target_platform }} =={{ version }}
        - cccl =={{ cccl_version }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      requires:
        - cmake  # [linux]
      files:
        - verify-version.cmake  # [linux]
      commands:
        - test -d $PREFIX/lib/cmake                      # [linux]
        - test -d $PREFIX/targets/{{ target_name }}/lib  # [linux]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cmake exit 1    # [win]
        - if not exist %LIBRARY_INC%\targets\{{ target_name }} exit 1  # [win]
        # Extract the CCCL version from the cuda_cccl archive, and compare to the
        # version of the cccl conda package.
        - '[[ "$(cmake -DCCCL_VERSION_FILE="$PREFIX/targets/{{ target_name }}/lib/cmake/cccl/cccl-config-version.cmake" -P verify-version.cmake)" == "{{ cccl_version }}" ]] || exit 1'  # [linux]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: 'CUDA C++ Core Libraries'
      description: |
        CUDA C++ Core Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

  - name: cuda-cccl_{{ target_platform }}
    build:
      noarch: generic
    files:
      - targets  # [linux]
      - Library\lib\x64\cmake                      # [win]
      - Library\include\targets\{{ target_name }}  # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -d $PREFIX/targets/{{ target_name }}/lib      # [linux]
        - test -d $PREFIX/targets/{{ target_name }}/include  # [linux]
        - if not exist %LIBRARY_LIB%\{{ target_name }}\cmake exit 1    # [win]
        - if not exist %LIBRARY_INC%\targets\{{ target_name }} exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: 'CUDA C++ Core Libraries'
      description: |
        CUDA C++ Core Libraries
      doc_url: https://docs.nvidia.com/cuda/index.html

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: 'CUDA C++ Core Libraries'
  description: |
    CUDA C++ Core Libraries
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
